baseURL = "http://example.org/"
languageCode = "en-us"
title = "qe-camp 2020"

enableEmoji = true
enableMissingTranslationPlaceholders = true
enableGitInfo = true

# 导航栏的定义，已经分页面的名称
[menu]

  [[menu.main]]
    identifier = "home"
    name = "HOME"
    title = "home section"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "speakers"
    name = "SPEAKERS"
    title = "speaker section"
    url = "/speakers/"
    weight = 20

  [[menu.main]]
    identifier = "updates"
    name = "UPDATES"
    title = "updates section"
    url = "/updates/"
    weight = 30

  [[menu.main]]
    identifier = "schedule"
    name = "SCHEDULE"
    title = "schedule section"
    url = "/schedule/"
    weight = 40

  [[menu.main]]
    identifier = "faqs"
    name = "FAQS"
    title = "fags section"
    url = "/faqs/"
    weight = 50


# 自定义的参数
[params.meeting]

  start_date = "October 3rd, 2020"
  location = "Raycom North Tower, Beijing China"

[params.venue]

  name = "Raycom Infotech Park"
  desc = "Raycom Info Tech Park located at Zhong Guan Cun Central industrial and business zone, with a total area of 328,000 square meter. The whole park is a combination of 4 office and commercial buildings at international A grading standard and 2 hotel-and appartments, with international level management."
  address = "No.2 KeXueYuan Nanlu,Haidian District,Beijing, China 100190"


[params]

  [[params.speaker]]
    name = "Wei Shi"
    company = "Virt, Redhat"
    location = "Beijing, China"
    avatar = "/img/avatar/demo02.jpg"

  [[params.speaker]]
    name = "Jianwei Hou"
    company = "Openshift, Redhat"
    location = "Beijing, China"
    avatar = "/img/avatar/demo02.jpg"

  [[params.speaker]]
    name = "Yaning Wang"
    company = "RHVH, Redhat"
    location = "Beijing, China"
    avatar = "/img/avatar/demo02.jpg"

  [[params.speaker]]
    name = "John Doe"
    company = "Devops, Redhat"
    location = "Beijing, China"
    avatar = "/img/avatar/demo02.jpg"


  [[params.ticket]]
    price = "100 ￥"
    desc = "total 200 places"
    status = "SOLD OUT"

  [[params.ticket]]
    price = "500 ￥"
    desc = "total 100 places"
    status = "SOLD OUT"

  [[params.ticket]]
    price = "800 ￥"
    desc = "total 50 places"
    status = "SOLD OUT"

# FAQs

  [[params.faqs]]
    question = "Are the talks recorded or live-streamed?"
    answer = "lorem loremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem"
    tag = "General Questions"

  [[params.faqs]]
    question = "Are the talks recorded or live-streamed?"
    answer = "lorem loremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem"
    tag = "General Questions"

  [[params.faqs]]
    question = "Are the talks recorded or live-streamed?"
    answer = "lorem loremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem"
    tag = "General Questions"

  [[params.faqs]]
    question = "Where is the schedule? When will the Schedule be ready?"
    answer = "loremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem"
    tag = "Schedule/CfP Questions"

  [[params.faqs]]
    question = "Where is the schedule? When will the Schedule be ready?"
    answer = "loremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem"
    tag = "Schedule/CfP Questions"

  [[params.faqs]]
    question = "Where is the schedule? When will the Schedule be ready?"
    answer = "loremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem"
    tag = "Schedule/CfP Questions"

  [[params.faqs]]
    question = "Where is the schedule? When will the Schedule be ready?"
    answer = "loremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem"
    tag = "Schedule/CfP Questions"

  [[params.faqs]]
    question = "What is going on with trains to/from Beijing? I heard there was construction."
    answer = "loremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem"
    tag = "tick"

  [[params.faqs]]
    question = "What is going on with trains to/from Beijing? I heard there was construction."
    answer = "loremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremloremlorem"
    tag = "tick"
